ALTER TABLE users
    MODIFY user_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE accounts
    MODIFY account_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE admin_logs
    MODIFY admin_log_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE coupons
    MODIFY coupon_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE manifests
    MODIFY manifest_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE message_logs
    MODIFY message_log_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE ships
    MODIFY ship_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE schedules
    MODIFY schedule_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE reservations
    MODIFY reservation_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE oauth2_users
    MODIFY oauth2_user_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE refresh_tokens
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT;